apiVersion: v1
kind: ConfigMap
metadata:
  name: middle-config
data:
  DB_URL: jdbc:postgresql://middle-postgres:5432/remitcore
  DB_NAME: remitcore
---
apiVersion: v1
kind: Secret
metadata:
  name: middle-secret
type: Opaque
stringData:
  DB_USER: remitcore
  DB_PASSWORD: remitcore
